name: Coverage
on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Run tests with coverage
      run: go test -v -covermode=count -coverprofile=coverage.out ./...

    - name: List files
      run: ls -la

    - name: Install goveralls
      run: |
        go install github.com/mattn/goveralls@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Coveralls
      run: goveralls -coverprofile=coverage.out -service=github -repotoken ${{ secrets.COVERALLS_TOKEN }}
