name: Coverage
on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Install gocov
      run: |
        go get github.com/axw/gocov/gocov
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Test and generate coverage data
      run: |
        go test -coverprofile=coverage.out ./...

    - name: Convert coverage data to gocov's JSON format
      run: |
        gocov convert coverage.out > coverage.json

    - name: Install gocov-to-cobertura
      run: |
        go get github.com/AlekSi/gocov-xml
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Convert coverage report to Cobertura format
      run: gocov-xml < coverage.json > coverage.xml

    - name: Install coveralls
      run: |
        go get github.com/mattn/goveralls
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Send coverage report to Coveralls
      run: |
        goveralls -coverprofile=coverage.xml -service=github -repotoken ${{ secrets.COVERALLS_TOKEN }}
