name: Coverage
on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install go-acc
        run: go install github.com/ory/go-acc@latest

      - name: Install gocov-xml
        run: go install github.com/AlekSi/gocov-xml@latest

      - name: Run tests with coverage
        run: go-acc ./... -- -race -covermode=atomic -coverprofile=coverage.out

      - name: Convert coverage profile to Cobertura XML
        run: gocov convert coverage.out | gocov-xml > coverage.xml

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          path-to-lcov: coverage.xml
