name: Go

on:
   push:
    branches: [main, release-*]
   pull_request:
    branches: [main, release-*]

jobs:
 go_fmt:
    name: Gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
         gofmt-path: './src'
         gofmt-flags: '-l -d'
      - run: gofmt -l -e -s ./
      
      - name: Run tests
        run: go test ./test/...
        

        
